# Generated by Django 5.0.2 on 2024-02-19 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('telefono', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('horario_laboral', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('DISP', 'Disponible'), ('NODISP', 'No Disponible')], default='DISP', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cita', models.DateField()),
                ('horario', models.TimeField(blank=True, null=True)),
                ('servicio', models.CharField(blank=True, max_length=25, null=True)),
                ('metodo_pago', models.CharField(blank=True, max_length=15, null=True)),
                ('paquete', models.CharField(blank=True, max_length=2, null=True)),
                ('total_sesiones', models.CharField(blank=True, max_length=1, null=True)),
                ('sesiones_tomadas', models.CharField(blank=True, max_length=1, null=True)),
                ('sesiones_faltantes', models.CharField(blank=True, max_length=1, null=True)),
                ('asignado_a', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('ACT', 'Activo'), ('CAN', 'Cancelado'), ('REA', 'Reagendado'), ('PCON', 'Por Confirmar')], default='PCON', max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intranet.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='FichaClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('fecha_cita', models.DateField()),
                ('telefono', models.CharField(max_length=15)),
                ('edad', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ocupacion', models.CharField(blank=True, max_length=30, null=True)),
                ('motivo_consulta', models.CharField(blank=True, max_length=30, null=True)),
                ('cardiovasculares', models.CharField(blank=True, max_length=30, null=True)),
                ('pulmonares', models.CharField(blank=True, max_length=30, null=True)),
                ('digestivos', models.CharField(blank=True, max_length=30, null=True)),
                ('otros', models.CharField(blank=True, max_length=30, null=True)),
                ('sexo', models.CharField(blank=True, max_length=4, null=True)),
                ('estado_civil', models.CharField(blank=True, max_length=10, null=True)),
                ('renales', models.CharField(blank=True, max_length=30, null=True)),
                ('alergicos', models.CharField(max_length=30)),
                ('quirurgicos', models.CharField(max_length=30)),
                ('respiratorios', models.CharField(blank=True, max_length=30, null=True)),
                ('alcoholismo', models.CharField(blank=True, max_length=2, null=True)),
                ('tabaquismo', models.CharField(blank=True, max_length=2, null=True)),
                ('drogas', models.CharField(blank=True, max_length=20, null=True)),
                ('otro', models.CharField(blank=True, max_length=20, null=True)),
                ('madre', models.CharField(blank=True, max_length=2, null=True)),
                ('enfermed_madre', models.CharField(blank=True, max_length=30, null=True)),
                ('padre', models.CharField(blank=True, max_length=2, null=True)),
                ('enfermed_padre', models.CharField(blank=True, max_length=30, null=True)),
                ('inicio_menstruacion', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ciclo_menstruacion', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('duracion_menstruacion', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ultima_regla', models.DateField(blank=True, null=True)),
                ('anticonceptivos', models.CharField(blank=True, max_length=2, null=True)),
                ('menopausia', models.CharField(blank=True, max_length=2, null=True)),
                ('exploracion_fisica', models.CharField(blank=True, max_length=35, null=True)),
                ('peso', models.FloatField()),
                ('talla', models.FloatField()),
                ('imc', models.FloatField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intranet.cliente')),
            ],
        ),
    ]
