# Generated by Django 5.0.2 on 2024-03-19 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=35)),
                ('horario_laboral_inicio', models.TimeField(default='00:00')),
                ('horario_laboral_fin', models.TimeField(default='00:00')),
                ('status', models.CharField(choices=[('disponible', 'Disponible'), ('no_disponible', 'No Disponible')], default='disponible', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='FichaClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ficha', models.DateTimeField(blank=True, null=True)),
                ('edad', models.IntegerField()),
                ('ocupacion', models.CharField(blank=True, max_length=30, null=True)),
                ('motivo_consulta', models.CharField(max_length=30)),
                ('cardiovasculares', models.CharField(max_length=20)),
                ('pulmonares', models.CharField(max_length=20)),
                ('digestivos', models.CharField(max_length=20)),
                ('otros', models.CharField(max_length=20)),
                ('sexo', models.CharField(blank=True, max_length=2, null=True)),
                ('estado_civil', models.CharField(blank=True, max_length=10, null=True)),
                ('renales', models.CharField(max_length=20)),
                ('alergicos', models.CharField(max_length=30)),
                ('quirurgicos', models.CharField(max_length=20)),
                ('respiratorios', models.CharField(max_length=20)),
                ('alcoholismo', models.CharField(blank=True, max_length=10, null=True)),
                ('tabaquismo', models.CharField(blank=True, max_length=10, null=True)),
                ('drogas', models.CharField(blank=True, max_length=2, null=True)),
                ('otro', models.CharField(blank=True, max_length=10, null=True)),
                ('madre', models.CharField(blank=True, max_length=2, null=True)),
                ('enfermed_madre', models.CharField(max_length=30)),
                ('padre', models.CharField(blank=True, max_length=2, null=True)),
                ('enfermed_padre', models.CharField(max_length=30)),
                ('inicio_menstruacion', models.IntegerField(blank=True, null=True)),
                ('ciclo_menstruacion', models.IntegerField(blank=True, null=True)),
                ('duracion_menstruacion', models.IntegerField(blank=True, null=True)),
                ('ultima_regla', models.DateTimeField(blank=True, null=True)),
                ('anticonceptivos', models.CharField(blank=True, max_length=15, null=True)),
                ('menopausia', models.CharField(blank=True, max_length=2, null=True)),
                ('peso', models.FloatField()),
                ('talla', models.FloatField()),
                ('imc', models.FloatField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intranet.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cita', models.DateTimeField()),
                ('horario_cita_inicio', models.TimeField(default='00:00')),
                ('horario_cita_fin', models.TimeField(default='00:00')),
                ('servicio', models.CharField(max_length=25)),
                ('metodo_pago', models.CharField(max_length=15)),
                ('paquete', models.CharField(max_length=2)),
                ('total_sesiones', models.CharField(blank=True, max_length=2, null=True)),
                ('sesiones_tomadas', models.CharField(blank=True, max_length=2, null=True)),
                ('sesiones_faltantes', models.CharField(blank=True, max_length=2, null=True)),
                ('status', models.CharField(choices=[('por_confirmar', 'Por confirmar'), ('asistio', 'Asistio'), ('cancelada', 'Cancelada'), ('reagendada', 'Reagendada')], default='por_confirmar', max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intranet.cliente')),
                ('asignado_a', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='citas_asignadas', to='intranet.personal')),
            ],
        ),
    ]
