# Generated by Django 5.0.3 on 2024-03-31 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cita',
            old_name='cliente',
            new_name='nombre_cliente',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='nombre',
            new_name='nombre_cliente',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='telefono',
            new_name='telefono_cliente',
        ),
        migrations.RenameField(
            model_name='fichaclinica',
            old_name='cliente',
            new_name='nombre_cliente',
        ),
        migrations.RenameField(
            model_name='personal',
            old_name='nombre',
            new_name='nombre_empleado',
        ),
        migrations.AddField(
            model_name='cita',
            name='observaciones',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
