# Generated by Django 5.0.2 on 2024-03-01 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='asignado_a',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='citas_asignadas', to='intranet.personal'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='metodo_pago',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='cita',
            name='paquete',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='cita',
            name='servicio',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='cita',
            name='sesiones_faltantes',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AlterField(
            model_name='cita',
            name='sesiones_tomadas',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AlterField(
            model_name='cita',
            name='status',
            field=models.CharField(choices=[('por_confirmar', 'Por confirmar'), ('asistio', 'Asistio'), ('cancelada', 'Cancelada'), ('reagendada', 'Reagendada')], default='por_confirmar', max_length=20),
        ),
        migrations.AlterField(
            model_name='cita',
            name='total_sesiones',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AlterField(
            model_name='fichaclinica',
            name='alcoholismo',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='fichaclinica',
            name='anticonceptivos',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='fichaclinica',
            name='cardiovasculares',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='fichaclinica',
            name='ciclo_menstruacion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fichaclinica',
            name='digestivos',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='fichaclinica',
            name='drogas',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='fichaclinica',
            name='duracion_menstruacion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fichaclinica',
            name='edad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fichaclinica',
            name='enfermed_madre',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='fichaclinica',
            name='enfermed_padre',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='fichaclinica',
            name='estado_civil',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='fichaclinica',
            name='exploracion_fisica',
            field=models.CharField(blank=True, max_length=35),
        ),
        migrations.AlterField(
            model_name='fichaclinica',
            name='inicio_menstruacion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fichaclinica',
            name='madre',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='fichaclinica',
            name='menopausia',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='fichaclinica',
            name='motivo_consulta',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='fichaclinica',
            name='ocupacion',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='fichaclinica',
            name='otro',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='fichaclinica',
            name='otros',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='fichaclinica',
            name='padre',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='fichaclinica',
            name='pulmonares',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='fichaclinica',
            name='renales',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='fichaclinica',
            name='respiratorios',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='fichaclinica',
            name='sexo',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='fichaclinica',
            name='tabaquismo',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='personal',
            name='horario_laboral',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='personal',
            name='status',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('no_disponible', 'No Disponible')], default='disponible', max_length=20),
        ),
    ]
