# Generated by Django 5.0.3 on 2024-04-06 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0002_rename_cliente_cita_nombre_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='observaciones',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fichaclinica',
            name='alcoholismo',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='fichaclinica',
            name='anticonceptivos',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fichaclinica',
            name='cardiovasculares',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='fichaclinica',
            name='digestivos',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='fichaclinica',
            name='enfermed_madre',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='fichaclinica',
            name='enfermed_padre',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='fichaclinica',
            name='motivo_consulta',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='fichaclinica',
            name='ocupacion',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='fichaclinica',
            name='otro',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='fichaclinica',
            name='otros',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='fichaclinica',
            name='pulmonares',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='fichaclinica',
            name='quirurgicos',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='fichaclinica',
            name='renales',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='fichaclinica',
            name='respiratorios',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='fichaclinica',
            name='sexo',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='fichaclinica',
            name='tabaquismo',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
