# Generated by Django 5.0.3 on 2024-04-08 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0003_alter_cita_observaciones_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichaclinica',
            name='sexo',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
